### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by HenriTEL** [loomnetwork/gamechain#431]
The git@github.com:loomnetwork/loomauth.git dependency does not exist in Makefile (`make deps` breaks).

**Comment by edenweb1** [comment]
Hello, Same problem here

**Comment by edenweb1** [comment]
> The [git@github.com](mailto:git@github.com):loomnetwork/loomauth.git dependency does not exist in Makefile (`make deps` breaks).

Same problem here bro, did you find a way to fix it?

**Comment by HangYang** [comment]
@HenriTEL @edenweb1 that's known issue, we will get it fixed early next week.

**Comment by edenweb1** [comment]
Hello Hang, thank you, it seems to be fixed for the loomauth repo.
but always the problem mentioned here : https://github.com/loomnetwork/gamechain/issues/432

**Comment by HenriTEL** [comment]
Thank you for the fi @HangYang
