### ISSUE TITLE
cannot find package "github.com/ethereum/go-ethereum/crypto/sha3

### ISSUE THREAD

**Issue by edenweb1** [loomnetwork/gamechain#432]
hello, i get this error when running make deps :
"
cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/usr/lib/go-1.10/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/root/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
Makefile:204: recipe for target 'deps' failed
make[1]: *** [deps] Error 1
make[1]: Leaving directory '/src/github.com/loomnetwork/loomchain'
Makefile:102: recipe for target 'deps' failed
make: *** [deps] Error 2 "

i followed all the steps gived on https://loomx.io/developers/en/relentless.html#build-the-relentless-smart-contract.

Any idea of how to solve it?  
maybe see here can help to fix the makefile : https://github.com/ethereum/go-ethereum/issues/19320
thanks in advance

**Comment by HenriTEL** [comment]
I think you misconfigured your GOPATH (step 2 an 3 in https://loomx.io/developers/en/relentless.html#getting-started)

**Comment by edenweb1** [comment]
> I think you misconfigured your GOPATH (step 2 an 3 in https://loomx.io/developers/en/relentless.html#getting-started)

Thank you VM, but i exactly followed all the steps on 2 different server. And same error. Wich version of go do you recommend to use please?

**Comment by edenweb1** [comment]
It work for me now. Resolved the issue by reinstalling go with the command "sudo snap install go"

**Comment by HangYang** [comment]
@edenweb1 thx. I will close the issue then
